name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello"
          echo "World"
      - name: Print Good bye
        run: echo "Done -> Good bye!"
